/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/keyboard.glb --types
Author: FoxFX (https://sketchfab.com/FoxFXMD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/razer-huntsman-mini-keyboard-d5a3d193b5f343e69eaa1a4d061b66f7
Title: Razer Huntsman Mini Keyboard
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Keycaps_Keycaps_0: THREE.Mesh;
    Stabilizers_Stabilizers_0: THREE.Mesh;
    LED_LED_0: THREE.Mesh;
    Wire_Wire_0: THREE.Mesh;
    Stabilizer_slots_Stabilizer_slots_0: THREE.Mesh;
    Case_Case_0: THREE.Mesh;
    ["6_Degrees_6_Degrees_0"]: THREE.Mesh;
    ["9_Degrees_9_Degrees_0"]: THREE.Mesh;
    Cable_Cable_0: THREE.Mesh;
    Stem_Stem_0: THREE.Mesh;
    Housing_Housing_0: THREE.Mesh;
  };
  materials: {
    Keycaps: THREE.MeshStandardMaterial;
    Stabilizers: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Wire: THREE.MeshStandardMaterial;
    Stabilizer_slots: THREE.MeshStandardMaterial;
    Case: THREE.MeshStandardMaterial;
    ["6_Degrees"]: THREE.MeshStandardMaterial;
    ["9_Degrees"]: THREE.MeshStandardMaterial;
    Cable: THREE.MeshStandardMaterial;
    Stem: THREE.MeshStandardMaterial;
    Housing: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Keyboard(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/model/keyboard.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Keycaps_Keycaps_0.geometry}
        material={materials.Keycaps}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Stabilizers_Stabilizers_0.geometry}
        material={materials.Stabilizers}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.LED_LED_0.geometry}
        material={materials.material}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Wire_Wire_0.geometry}
        material={materials.Wire}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Stabilizer_slots_Stabilizer_slots_0.geometry}
        material={materials.Stabilizer_slots}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Case_Case_0.geometry}
        material={materials.Case}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes["6_Degrees_6_Degrees_0"].geometry}
        material={materials["6_Degrees"]}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes["9_Degrees_9_Degrees_0"].geometry}
        material={materials["9_Degrees"]}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Cable_Cable_0.geometry}
        material={materials.Cable}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Stem_Stem_0.geometry}
        material={materials.Stem}
        position={[-3.953, 1.646, -52.399]}
      />
      <mesh
        geometry={nodes.Housing_Housing_0.geometry}
        material={materials.Housing}
        position={[-3.953, 1.646, -52.399]}
      />
    </group>
  );
}

useGLTF.preload("/model/keyboard.glb");
