/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/pokemon.glb --types
Author: Nick Pekarsky (https://sketchfab.com/kolumba1991)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-masters-cap-892e724659c44d6c8771252523075b54
Title: Pokemon master's cap
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    LOW_Material_0: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Pokemon(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/model/pokemon.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.LOW_Material_0.geometry}
        material={materials.Material}
        position={[17.043, 0, 0]}
        rotation={[-1.355, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/model/pokemon.glb");
