/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/trophy.glb --types
Author: Esther3D (https://sketchfab.com/Esther3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trophy-model-4f00ff021b834b248849e74a8698a39d
Title: Trophy Model
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Handle_Handles_Texture_0: THREE.Mesh;
    Cup_Cup_Texture_0: THREE.Mesh;
    Base_Base_Texture_0: THREE.Mesh;
  };
  materials: {
    Handles_Texture: THREE.MeshStandardMaterial;
    Cup_Texture: THREE.MeshStandardMaterial;
    Base_Texture: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Trophy(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/model/trophy.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={40}>
            <group scale={2.5}>
              <group position={[0, 0, 0.226]}>
                <mesh
                  geometry={nodes.Cup_Cup_Texture_0.geometry}
                  material={materials.Cup_Texture}
                />
                <mesh
                  geometry={nodes.Handle_Handles_Texture_0.geometry}
                  material={materials.Handles_Texture}
                />
              </group>
              <mesh
                geometry={nodes.Base_Base_Texture_0.geometry}
                material={materials.Base_Texture}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/trophy.glb");
